
all:
	rm -f ABB-11 ABB-11_more
	g++ -O0 -g3  Data.cpp  Data.h  EmptyException.cpp  EmptyException.h  Learner.cpp  Learner.h  program.cpp -o ABB-11
	g++ -O0 -g3  Data.cpp  Data.h  EmptyException.cpp  EmptyException.h  Learner.cpp  Learner.h  program_moreBehavior.cpp -o ABB-11_more

